const avatarBaseURL = "/src/assets/animals/";

export const avatars = [
  { name: "Antelope", url: `${avatarBaseURL}antelope.svg` },
  { name: "Bear", url: `${avatarBaseURL}bear.svg` },
  { name: "Beaver", url: `${avatarBaseURL}beaver.svg` },
  { name: "Bull", url: `${avatarBaseURL}bull.svg` },
  { name: "Cat Grey", url: `${avatarBaseURL}cat-grey.svg` },
  { name: "Cat Orange", url: `${avatarBaseURL}cat-orange.svg` },
  { name: "Chipmunk", url: `${avatarBaseURL}chipmunk.svg` },
  { name: "Cow", url: `${avatarBaseURL}cow.svg` },
  { name: "Deer", url: `${avatarBaseURL}deer.svg` },
  { name: "Donkey", url: `${avatarBaseURL}donkey.svg` },
  { name: "Duck", url: `${avatarBaseURL}duck.svg` },
  { name: "Giraffe", url: `${avatarBaseURL}giraffe.svg` },
  { name: "Goat", url: `${avatarBaseURL}goat.svg` },
  { name: "Goose", url: `${avatarBaseURL}goose.svg` },
  { name: "Hare", url: `${avatarBaseURL}hare.svg` },
  { name: "Horse", url: `${avatarBaseURL}horse.svg` },
  { name: "Kangaroo", url: `${avatarBaseURL}kangaroo.svg` },
  { name: "Leopard", url: `${avatarBaseURL}leopard.svg` },
  { name: "Lizard", url: `${avatarBaseURL}lizard.svg` },
  { name: "Moose", url: `${avatarBaseURL}moose.svg` },
  { name: "Ox", url: `${avatarBaseURL}ox.svg` },
  { name: "Pegasus", url: `${avatarBaseURL}pegasus.svg` },
  { name: "Pig", url: `${avatarBaseURL}pig.svg` },
  { name: "Raccoon", url: `${avatarBaseURL}raccoon.svg` },
  { name: "Ram", url: `${avatarBaseURL}ram.svg` },
  { name: "Sheep", url: `${avatarBaseURL}sheep.svg` },
  { name: "Unicorn", url: `${avatarBaseURL}unicorn.svg` },
  { name: "Wolf", url: `${avatarBaseURL}wolf.svg` },
  { name: "Zebra", url: `${avatarBaseURL}zebra.svg` },
];
